import type { Theme, Font, MusicTrack } from './types';

export const themes: Theme[] = [
    {
        name: 'Classic Cyan',
        background: '#000000',
        clockBackground: 'rgba(17, 24, 39, 0.7)',
        borderColor: '#374151',
        textColor: '#67e8f9',
        colonColor: '#22d3ee',
        dateColor: '#0891b2',
        buttonBg: 'rgba(55, 65, 81, 0.5)',
        buttonColor: '#22d3ee',
        buttonBorder: '#4b5563',
    },
    {
        name: 'Vintage Amber',
        background: '#1c1917',
        clockBackground: 'rgba(28, 25, 23, 0.7)',
        borderColor: '#57534e',
        textColor: '#fcd34d',
        colonColor: '#fbbf24',
        dateColor: '#f59e0b',
        buttonBg: 'rgba(41, 37, 36, 0.5)',
        buttonColor: '#fbbf24',
        buttonBorder: '#57534e',
    },
    {
        name: 'Matrix Green',
        background: '#000000',
        clockBackground: 'rgba(10, 20, 10, 0.7)',
        borderColor: '#166534',
        textColor: '#4ade80',
        colonColor: '#22c55e',
        dateColor: '#16a34a',
        buttonBg: 'rgba(22, 101, 52, 0.5)',
        buttonColor: '#4ade80',
        buttonBorder: '#166534',
    },
    {
        name: 'Ruby Red',
        background: '#1e0000',
        clockBackground: 'rgba(30, 0, 0, 0.7)',
        borderColor: '#991b1b',
        textColor: '#f87171',
        colonColor: '#ef4444',
        dateColor: '#dc2626',
        buttonBg: 'rgba(127, 29, 29, 0.5)',
        buttonColor: '#f87171',
        buttonBorder: '#991b1b',
    },
    {
        name: 'Plasma Purple',
        background: '#1e0b2a',
        clockBackground: 'rgba(30, 11, 42, 0.7)',
        borderColor: '#6b21a8',
        textColor: '#d8b4fe',
        colonColor: '#c084fc',
        dateColor: '#a855f7',
        buttonBg: 'rgba(91, 33, 182, 0.5)',
        buttonColor: '#d8b4fe',
        buttonBorder: '#6b21a8',
    },
    {
        name: 'Arctic Blue',
        background: '#0c1425',
        clockBackground: 'rgba(12, 20, 37, 0.7)',
        borderColor: '#1e3a8a',
        textColor: '#dbeafe',
        colonColor: '#93c5fd',
        dateColor: '#60a5fa',
        buttonBg: 'rgba(30, 58, 138, 0.5)',
        buttonColor: '#dbeafe',
        buttonBorder: '#1e3a8a',
    },
    {
        name: 'Sunset Orange',
        background: '#2c1302',
        clockBackground: 'rgba(44, 19, 2, 0.7)',
        borderColor: '#9a3412',
        textColor: '#fdba74',
        colonColor: '#fb923c',
        dateColor: '#f97316',
        buttonBg: 'rgba(124, 45, 18, 0.5)',
        buttonColor: '#fdba74',
        buttonBorder: '#9a3412',
    },
    {
        name: 'Emerald Forest',
        background: '#061d10',
        clockBackground: 'rgba(6, 29, 16, 0.7)',
        borderColor: '#065f46',
        textColor: '#6ee7b7',
        colonColor: '#34d399',
        dateColor: '#10b981',
        buttonBg: 'rgba(5, 150, 105, 0.5)',
        buttonColor: '#6ee7b7',
        buttonBorder: '#065f46',
    },
    {
        name: 'Ghost White',
        background: '#4b5563',
        clockBackground: 'rgba(17, 24, 39, 0.7)',
        borderColor: '#9ca3af',
        textColor: '#f9fafb',
        colonColor: '#e5e7eb',
        dateColor: '#d1d5db',
        buttonBg: 'rgba(55, 65, 81, 0.5)',
        buttonColor: '#f9fafb',
        buttonBorder: '#9ca3af',
    },
    {
        name: 'Hot Pink',
        background: '#2c021a',
        clockBackground: 'rgba(44, 2, 26, 0.7)',
        borderColor: '#9d174d',
        textColor: '#f9a8d4',
        colonColor: '#f472b6',
        dateColor: '#ec4899',
        buttonBg: 'rgba(131, 24, 67, 0.5)',
        buttonColor: '#f9a8d4',
        buttonBorder: '#9d174d',
    },
];

export const fonts: Font[] = [
    { name: 'Bungee', styleName: "'Bungee', cursive" },
    { name: 'Audiowide', styleName: "'Audiowide', cursive" },
    { name: 'Viga', styleName: "'Viga', sans-serif" },
    { name: 'Concert One', styleName: "'Concert One', cursive" },
];

export const musicTracks: MusicTrack[] = [
     { 'title': 'Music To Relax', 'url': 'https://music-to-relax.stream.laut.fm/music-to-relax' },
     { 'title': 'Radio Relax International', 'url': 'https://radio.tvstitch.com/RadioRelax_Int' },
     { 'title': 'EPIC CLASSICAL - Restaurant', 'url': 'https://stream.epic-classical.com/classical-restaurant-music' },
     { 'title': 'EPIC CLASSICAL - Relax', 'url': 'https://stream.epic-classical.com/classical-relax' },
     { 'title': 'Beautiful Music 101', 'url': 'https://radio.streemlion.com:1665/stream' },
     { 'title': 'Soundstorm - Relax Radio', 'url': 'http://stream.soundstorm-radio.com/radio/8000/radio.mp3' },
     { 'title': 'VOA English', 'url': 'http://voa-28.akacast.akamaistream.net/7/54/322040/v1/ibb.akacast.akamaistream.net/voa-28.m3u' },
     { 'title': 'Podcast Radio', 'url': 'https://podcastradio.cdnstream1.com/world' },
     { 'title': 'Podcast Radio Business', 'url': 'https://ais-sa8.cdnstream1.com/2747_192.mp3' },
     { 'title': 'Radio Samleng Khemara', 'url': 'http://radio.khemaranet.com:7580/' },
     { 'title': 'Daun Penh EFM', 'url': 'http://203.189.159.204:9051/dpnefmpp' },
     { 'title': 'RFI Anglais', 'url': 'https://rfianglais96k.ice.infomaniak.ch/rfianglais-96k.mp3' },
     { 'title': 'Quran in English', 'url': 'http://quraan.us:9990' },
     { 'title': 'Open Radio Usa', 'url': 'https://stream.zeno.fm/20catahb6d4uv' },
     { 'title': 'Radio USA', 'url': 'https://playerservices.streamtheworld.com/api/livestream-redirect/WUSZFM.mp3' },
     { 'title': 'Old Time Radio USA', 'url': 'https://fwd.autopo.st/otrusa' },
     { 'title': 'RNK Radio National Kampuchea', 'url': 'http://119.82.252.6:8080/broadwave.mp3' },
     { 'title': 'Vayo FM', 'url': 'http://50.21.176.38:8010/vayofm/;' },
     { 'title': 'RNK FM', 'url': 'http://119.82.252.6:8181/broadwave.mp3' },
];